Studenpläne
fsi-tue/anfibrief pull request #42
Opened 2020-09-17 18:15 UTC by zhavan

Hab hier die Stundenpläne für Info, Lehramt, Medizininfo und Medieninfo schonmal geupdatet. Zudem auch noch n paar Termine

2020-09-19 18:38 UTC, luoe commented
YAY! It finally builds :partying_face:

2020-09-19 19:37 UTC, PhictionalOne commented on src/termine.tex
> -	\\
That's it. That was all?! F**k me! I fixes everything but this? really?

2020-09-21 15:18 UTC, PhictionalOne requested changes
change '\Matheprof' to Ochs

2020-09-21 15:18 UTC, PhictionalOne commented on src/config.tex
> +\newcommand{\Matheprof}{TBA}
Will be Ochs

2020-09-21 15:53 UTC, luoe commented
> change '\Matheprof' to Ochs

Chill :D I already told Vanessa.

2020-09-22 18:44 UTC, PhictionalOne approved these changes

2020-09-25 21:56 UTC, merged